//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilimoHigh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DOB { get; set; }
        public int StreamId { get; set; }
        public string SirName { get; set; }
        public string SecondName { get; set; }
        public string Fname { get; set; }
        public string GurdianPhone { get; set; }
    
        public virtual ClassStream ClassStream { get; set; }
    }
}
